### ISSUE TITLE
Like-expected behaviour for maps val inside in

### ISSUE THREAD

**Issue by velios** [clojure-expectations/clojure-test#32]
Expectations uses the format (expect expected actual) for all tests. It looks convenient if we could check the values inside the keys expected-way. 

```clojure
(expect {:foo 1 :bar #"foo" :baz integer? :not-checked-key :any-value}
        (in {:foo 1 :bar "boofooar" :baz 8}))
````

**Comment by seancorfield** [comment]
I have no plans to extend `in` like that but a PR is always welcome.

**Comment by velios** [comment]
Is this also true for nested maps with an open specification?
```clojure
(expect {:foo {:bar 1 :baz 2}
        (in {:foo {:bar 1}))
```
Now such a test will fail, but I would like it be success
It's such common pattern and it focus reader on what really changes in test

In fact, there is already a [library](https://github.com/HealthSamurai/matcho) offering this approach. But expectations have many more important innovations than this. As I understand it, any PR is welcome and will be considered?

**Comment by seancorfield** [comment]
Any PR with tests and documentation updates, yes. I would _prefer_ to not introduce a dependency on another library tho'.

**Comment by velios** [comment]
I found [matcher-combinators](https://github.com/nubank/matcher-combinators) library from nubank, which seems to do everything needed and more and could probably be used with the expectations library. Therefore, it is probably not worth making another implementation of the same thing in the library and the problem can be closed, since the solution already exists. If only we mention this solution in the readme.

**Comment by seancorfield** [comment]
If you feel it would add value to draft some examples of using Expectations with that matcher-combinators library, I could add those to the Expectations docs? I'll leave that up to you, and you can submit a PR with a draft if you want, and I'll close this ticket out.
