### ISSUE TITLE
Improve README (add "why", clarify "what")

### ISSUE THREAD

**Issue by seancorfield** [clojure-expectations/clojure-test#33]
The README should be standalone and not depend on knowledge of "classic" Expectations.

It should also clearly answer the question: why should I use Expectations instead of `clojure.test`?

**Comment by seancorfield** [comment]
See Slack discussion https://clojurians.slack.com/archives/C053AK3F9/p1709703486629969

**Comment by NoahTheDuke** [comment]
This looks great, Sean, thanks for writing it up.
